services:
  library-api:
    container_name: library-api
    build:
      context: .
      dockerfile: LibrarySystem.Api/Dockerfile
#    ports:
#      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - GrpcSettings__ServiceUrl=http://library-grpc:8080
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - library-grpc
    networks:
      - library-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  library-grpc:
    container_name: library-grpc
    build:
      context: .
      dockerfile: LibrarySystem.Grpc/Dockerfile
#    ports:
#      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=librarydb;Username=user;Password=${DB_PASSWORD:-changeme_in_prod}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - library-net
    restart: unless-stopped

  db:
    container_name: library-db
    image: postgres:16.11-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme_in_prod}
      - POSTGRES_DB=librarydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d librarydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - library-net
    restart: always
      
  waf:
    build:
      context: ./waf
      dockerfile: Dockerfile
    container_name: library-waf
    restart: unless-stopped
    ports:
      - "80:80"
      - "9090:9090"
    environment:
      - BACKEND_HOST=library-api:8080
    volumes:
      - ./Waf/Caddyfile:/etc/caddy/Caddyfile
      - ./Waf/coraza.conf:/etc/coraza/coraza.conf
      - ./Waf/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/coraza/crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./logs/waf:/var/log/waf
    depends_on:
      - library-api
    networks:
      - library-net

volumes:
  postgres_data:
    
networks:
  library-net:
    driver: bridge