services:
  library-api:
    container_name: library-api
    build:
      context: .
      dockerfile: LibrarySystem.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcSettings__ServiceUrl=http://library-grpc:8080
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - library-grpc

  library-grpc:
    container_name: library-grpc
    build:
      context: .
      dockerfile: LibrarySystem.Grpc/Dockerfile
    ports:
      - "5001:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=librarydb;Username=user;Password=password
    depends_on:
      db:
          condition: service_healthy

  db:
    container_name: library-db
    image: postgres:16.11-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=librarydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d librarydb" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: